# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-04 00:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Syain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(default='000-0000-0000', max_length=13)),
                ('name', models.CharField(default='sei-mei', max_length=30)),
                ('corporation_name', models.CharField(default='corpration-name', max_length=30)),
                ('job_start', models.IntegerField(default=0, max_length=5)),
                ('job_end', models.IntegerField(default=0, max_length=5)),
                ('status', models.CharField(default='休暇', max_length=2)),
                ('min', models.IntegerField(default=14000, max_length=5)),
                ('max', models.IntegerField(default=18000, max_length=5)),
                ('overtime', models.IntegerField(default=0, max_length=6)),
            ],
        ),
    ]
