# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-11 22:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_test', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syain',
            name='job_end',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='syain',
            name='job_start',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='syain',
            name='max',
            field=models.IntegerField(default=18000),
        ),
        migrations.AlterField(
            model_name='syain',
            name='min',
            field=models.IntegerField(default=14000),
        ),
        migrations.AlterField(
            model_name='syain',
            name='overtime',
            field=models.IntegerField(default=0),
        ),
    ]
