# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-11 23:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SyainData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(default='000-0000-0000', max_length=13)),
                ('password', models.CharField(default='sei-mei', max_length=30)),
                ('name', models.CharField(default='sei-mei', max_length=30)),
                ('corporation_name', models.CharField(default='corpration-name', max_length=30)),
                ('date', models.DateField()),
                ('job_start', models.TimeField()),
                ('job_end', models.TimeField()),
                ('status', models.CharField(default='休暇', max_length=2)),
                ('min', models.TimeField()),
                ('max', models.TimeField()),
                ('overtime', models.TimeField()),
            ],
        ),
    ]
